---
collections:
  - name: arista.avd
    version: ">=6.3.0"
  - name: arista.eos
    version: ">=7.0.0"
  - name: ansible.netcommon
  - name: ansible.utils
  - name: ansible.posix
  - name: community.general
  - name: netbox.netbox
