---
# yamllint disable-line rule:line-length
# L3 Edge port definitions. This can be any port in the entire Fabric, where IP interfaces are defined.
l3_edge:
  # yamllint disable-line rule:line-length
  # Define a new IP pool that will be used to assign IP addresses to L3 Edge interfaces.
  p2p_links_ip_pools:
    - name: L3_Border_IP
      ipv4_pool: 172.31.254.0/24
  # yamllint disable-line rule:line-length
  # Define a new link profile which will match the IP pool, the used ASNs and include the defined interface into underlay routing
  p2p_links_profiles:
    - name: L3_Border_Profile
      ip_pool: L3_Border_IP
      include_in_underlay_protocol: true
      as: [65103, 65202]
  # yamllint disable-line rule:line-length
  # Define each P2P L3 link and link the nodes, the interfaces and the profile used.
  p2p_links:
    - id: 1
      nodes: [DC1-LEAF3A, DC2-LEAF2A]
      interfaces: [Ethernet56/1, Ethernet56/1]
      profile: L3_Border_Profile
    - id: 2
      nodes: [DC1-LEAF3B, DC2-LEAF2B]
      interfaces: [Ethernet56/1, Ethernet56/1]
      profile: L3_Border_Profile
