---
# Host endpoint group variables
# Common settings for all DC hosts

# Output directory for generated configurations
output_dir: AVD-information

# Host devices do not connect via httpapi
ansible_connection: local
