---
# Host endpoint group variables
# Common settings for all DC hosts

# Output directory for generated configurations
# Base output directory - all outputs go here
output_dir: "{{ playbook_dir | dirname }}/AVD-information"
# Subdirectories (relative to output_dir)
configs_dir: "{{ output_dir }}/configs"
structured_configs_dir: "{{ output_dir }}/structured_configs"

# Host devices do not connect via httpapi
ansible_connection: local
