---
mgmt_interface_vrf: default

spine:
  # Define variables for all nodes of this type
  defaults:
    # yamllint disable-line rule:line-length
    # Set the relevant platform as each platform has different default values in Ansible AVD
    platform: vEOS-lab
    loopback_ipv4_pool: 101.1.1.0/24
    bgp_as: 65100
  # Define variables per node
  nodes:
    - name: DC1-SPINE1
      # Unique identifier used for IP addressing and other algorithms
      id: 1
      # Node management interface IPv4 address
      mgmt_ip: 192.168.0.110/24
      serial_number: SN-DC1-SPINE1

    - name: DC1-SPINE2
      id: 2
      mgmt_ip: 192.168.0.111/24
      serial_number: SN-DC1-SPINE2

    - name: DC1-SPINE3
      id: 3
      mgmt_ip: 192.168.0.112/24
      serial_number: SN-DC1-SPINE3

l3leaf:
  defaults:
    # yamllint disable-line rule:line-length
    # Set the relevant platform as each platform has different default values in Ansible AVD
    platform: vEOS-lab
    # yamllint disable-line rule:line-length
    # Pool of IPv4 addresses to configure interface Loopback0 used for BGP EVPN sessions
    loopback_ipv4_pool: 101.1.1.0/24
    # Offset all assigned loopback IP addresses.
    loopback_ipv4_offset: 4
    # yamllint disable-line rule:line-length
    # Definition of pool of IPs to be used as Virtual Tunnel EndPoint (VXLAN origin and destination IPs)
    vtep_loopback_ipv4_pool: 101.1.2.0/24
    # yamllint disable-line rule:line-length
    # Ansible hostname of the devices used to establish neighborship (IP assignments and BGP peering)
    uplink_switches: ['DC1-SPINE1', 'DC1-SPINE2', 'DC1-SPINE3']
    # Definition of pool of IPs to be used in P2P links
    uplink_ipv4_pool: 172.31.250.0/24
    # Definition of pool of IPs to be used for MLAG peer-link connectivity
    mlag_peer_ipv4_pool: 10.255.129.64/27
    # iBGP Peering between MLAG peers
    mlag_peer_l3_ipv4_pool: 10.255.129.96/27
    # yamllint disable-line rule:line-length
    # Virtual router mac for VNIs assigned to Leaf switches in format xx:xx:xx:xx:xx:xx
    virtual_router_mac_address: 00:1c:73:00:00:99
    spanning_tree_priority: 4096
    spanning_tree_mode: mstp

  node_groups:
    - group: DC1_LEAF1
      bgp_as: 65101
      nodes:
        - name: DC1-LEAF1A
          id: 1
          mgmt_ip: 192.168.0.113/24
          serial_number: SN-DC1-LEAF1A
          uplink_switch_interfaces: [Ethernet1/1, Ethernet1/1, Ethernet1/1]
        - name: DC1-LEAF1B
          id: 2
          mgmt_ip: 192.168.0.114/24
          serial_number: SN-DC1-LEAF1B
          uplink_switch_interfaces: [Ethernet2/1, Ethernet2/1, Ethernet2/1]

    - group: DC1_LEAF2
      bgp_as: 65102
      nodes:
        - name: DC1-LEAF2A
          id: 3
          mgmt_ip: 192.168.0.115/24
          serial_number: SN-DC1-LEAF2A
          uplink_switch_interfaces: [Ethernet3/1, Ethernet3/1, Ethernet3/1]
        - name: DC1-LEAF2B
          id: 4
          mgmt_ip: 192.168.0.116/24
          serial_number: SN-DC1-LEAF2B
          uplink_switch_interfaces: [Ethernet4/1, Ethernet4/1, Ethernet4/1]

    - group: DC1_LEAF3
      bgp_as: 65103
      evpn_gateway:
        evpn_l2:
          enabled: true
        evpn_l3:
          enabled: true
          inter_domain: true
      structured_config:
        ethernet_interfaces:
          - name: Ethernet56/1
            flow_tracker:
              sampled: cloudvision
      nodes:
        - name: DC1-LEAF3A
          id: 5
          mgmt_ip: 192.168.0.117/24
          serial_number: SN-DC1-LEAF3A
          uplink_switch_interfaces: [Ethernet5/1, Ethernet5/1, Ethernet5/1]
          evpn_gateway:
            remote_peers:
              - hostname: DC2-LEAF2A
        - name: DC1-LEAF3B
          id: 6
          mgmt_ip: 192.168.0.118/24
          serial_number: SN-DC1-LEAF3B
          uplink_switch_interfaces: [Ethernet6/1, Ethernet6/1, Ethernet6/1]
          evpn_gateway:
            remote_peers:
              - hostname: DC2-LEAF2B
