name: 'Reset Dev Environment'

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'reset'
        # Default value if no value is explicitly provided
        default: 'reset'
        # Input has to be provided for the workflow to run
        required: false
        # The data type of the input
        type: string

jobs:
  Test:
    name: RESET
    runs-on: [self-hosted, dev]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
        with:
          # Git Personal Access Token for repository access
          token: ${{ secrets.TENANTS }}

      - name: Run AVD Dev Reset Makefile Target
        run: |
          make dev_reset
